version: '3.8'

services:
  # Main application
  aws-propuestas-v3:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_MCP_BASE_URL=http://mcp-services:8000
      - NEXT_PUBLIC_CORE_MCP_URL=http://mcp-services:8000/core
      - NEXT_PUBLIC_AWSDOCS_MCP_URL=http://mcp-services:8000/awsdocs
      - NEXT_PUBLIC_DIAGRAM_MCP_URL=http://mcp-services:8000/diagram
      - NEXT_PUBLIC_PRICING_MCP_URL=http://mcp-services:8000/pricing
      - NEXT_PUBLIC_CUSTOMDOC_MCP_URL=http://mcp-services:8000/customdoc
      - NEXT_PUBLIC_CFN_MCP_URL=http://mcp-services:8000/cfn
    depends_on:
      - mcp-services
    networks:
      - app-network

  # MCP Services (Mock for local development)
  mcp-services:
    image: nginx:alpine
    ports:
      - "8000:80"
    volumes:
      - ./docker/mcp-mock:/usr/share/nginx/html
      - ./docker/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  redis_data:
